---
- name: Query ISS api with Ansible
  hosts: planetexpress
  gather_facts: no     # set to true by default, runs the "setup" module
  
    
  tasks:
  - name: Print out to the screen
    uri:
      url: http://worldclockapi.com/api/json/est/now 
                      #http://api.open-notify.org/iss-now.json
    register: astrojson     # the "register" keyword is not part of the uri module
                              # just like the "become" keyword, this augments how a module executes
                              # in this case, we want to save the response returned by this module
                              # ALL modules in Ansible return data. Think of it as the "results" of how the
                              # task ran.
                              
  - name: Display the contents of the variable astrojson
    debug:
      var: astrojson                                         
  - name: Display just the json
    debug:
      var: astrojson.json.currentFileTime                          

