all:
  hosts: 
    bender:
      ansible_host: 10.10.2.3
      ansible_user: bender
  children:
    planetexpress:
      hosts:
        fry:
          ansible_host: 10.10.2.4
          ansible_user: fry
        zoidberg:
          ansible_host: 10.10.2.5
          ansible_user: zoidberg
          ansible_ssh_pass: alta3
      vars:
        ansible_python_interpreter: /usr/bin/python3

